---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          env:
            # Workaround for https://github.com/argoproj/argo-cd/issues/3547#issuecomment-624819065
            - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
              value: "0"
