issues:
  exclude-rules:
    - linters:
        - paralleltest
      text: "Function TestAcc"
    - linters:
        - tparallel
      text: "TestAcc"
    - linters:
        - unparam
      text: "always receives"
    - path: _test\.go
      linters:
        - contextcheck
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - paralleltest
    - predeclared
    - staticcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - vet
    - vetshadow
    - whitespace
    - wsl

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
  errorlint:
    errorf: false
  goconst:
    ignore-tests: true
    min-occurrences: 6
  gocritic:
    enabled-tags:
      - diagnostic
    disabled-tags:
      - style
      - performance
      - experimental
      - opinionated
  gomnd:
    settings:
      mnd:
        checks:
          - argument
        ignored-functions:
          # Terraform Plugin SDK
          - resource.Retry
          - schema.DefaultTimeout
          - validation.*
          # Terraform Plugin Framework
          - int64validator.*
          - listvalidator.*
          - stringvalidator.*
          - SetDefaultCreateTimeout
          - SetDefaultReadTimeout
          - SetDefaultUpdateTimeout
          - SetDefaultDeleteTimeout
          # Go
          - make
          - strconv.FormatFloat
          - strconv.FormatInt
          - strconv.ParseFloat
          - strconv.ParseInt
          - strings.SplitN
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - gomnd
      - paralleltest
      - tparallel
      - unparam
  predeclared:
    ignore: cap,close,copy,delete,len,new
  staticcheck:
    checks: ["all", "-SA1019"]
  stylecheck:
    checks: ["all", "-ST1005", "-ST1003"]

run:
  timeout: 5m
