name: 'Close stale Issues/PRs'
on:
  schedule:
    - cron: '30 12 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 10
          # Issue settings
          stale-issue-message: 'This issue is stale because of a lack of response from the original author. Please provide the requested feedback or this will be closed in 10 days.'
          any-of-issue-labels: 'answered,cannot-reproduce,invalid,needs-more-info'
          # PR Settings
          stale-pr-message: 'This pr is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 10 days.'